### ISSUE TITLE
Unable to build with out-of-the-box Nerves Tooling

### ISSUE THREAD

**Issue by joelbyler** [jjcarstens/replex#4]
Example project at joelbyler/try_replex

To recreate:
1) Clone [this repo](https://github.com/joelbyler/try_replex)
2) Get deps
```
$ MIX_TARGET=rpi0 mix deps..get
```
3) Build firmware
```
MIX_TARGET=rpi0 mix firmware
```

The following error results
```
Nerves environment
  MIX_TARGET:   rpi0
  MIX_ENV:      dev

==> replex
mkdir -p /Users/myuser/Workspaces/try_replex/_build/rpi0_dev/lib/replex/ebin/../priv
mkdir -p /Users/myuser/Workspaces/try_replex/_build/rpi0_dev/lib/replex/ebin/../obj
KCONFIG_NOTIMESTAMP=1 /usr/local/bin/gmake CROSS_COMPILE="/Users/myuser/.nerves/artifacts/nerves_toolchain_armv6_rpi_linux_gnueabi-darwin_x86_64-1.2.0/bin/armv6-rpi-linux-gnueabi-" SED=/usr/local/bin/gsed -C /Users/myuser/Workspaces/try_replex/deps/replex//src/librpitx-5475c41ccf202b544cac6cf0c670ae40210a9f4b/src
gmake[1]: Entering directory '/Users/myuser/Workspaces/try_replex/deps/replex/src/librpitx-5475c41ccf202b544cac6cf0c670ae40210a9f4b/src'
#cc -Wall -O3 -Wno-unused-variable -c -o mailbox.o mailbox.c
cc -Wall -O3 -Wno-unused-variable -c -o raspberry_pi_revision.o raspberry_pi_revision.c
c++ -std=c++11 -Wall -O3 -Wno-unused-variable -c dsp.cpp iqdmasync.cpp ngfmdmasync.cpp fmdmasync.cpp  dma.cpp gpio.cpp serialdmasync.cpp phasedmasync.cpp amdmasync.h amdmasync.cpp fskburst.cpp ookburst.cpp atv.cpp util.cpp mailbox.c
clang: warning: treating 'c-header' input as 'c++-header' when in C++ mode, this behavior is deprecated [-Wdeprecated]
clang: warning: treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated [-Wdeprecated]
In file included from dma.cpp:25:
./mailbox.h:30:10: fatal error: 'linux/ioctl.h' file not found
#include <linux/ioctl.h>
         ^~~~~~~~~~~~~~~
1 error generated.
In file included from gpio.cpp:19:
./mailbox.h:30:10: fatal error: 'linux/ioctl.h' file not found
#include <linux/ioctl.h>
         ^~~~~~~~~~~~~~~
1 error generated.
atv.cpp:161:41: error: cast from pointer to smaller type 'unsigned int' loses information
    dbg_printf(1, "Last cbp :  %d \n", ((unsigned int)(cbp) - (unsigned int)(cbarray)) / sizeof(dma_cb_t));
                                        ^~~~~~~~~~~~~~~~~~~
atv.cpp:161:63: error: cast from pointer to smaller type 'unsigned int' loses information
    dbg_printf(1, "Last cbp :  %d \n", ((unsigned int)(cbp) - (unsigned int)(cbarray)) / sizeof(dma_cb_t));
                                                              ^~~~~~~~~~~~~~~~~~~~~~~
2 errors generated.
mailbox.c:40:10: fatal error: 'sys/sysmacros.h' file not found
#include <sys/sysmacros.h>
         ^~~~~~~~~~~~~~~~~
1 error generated.
gmake[1]: *** [Makefile:10: librpitx] Error 1
gmake[1]: Leaving directory '/Users/myuser/Workspaces/try_replex/deps/replex/src/librpitx-5475c41ccf202b544cac6cf0c670ae40210a9f4b/src'
make: *** [/Users/myuser/Workspaces/try_replex/_build/rpi0_dev/lib/replex/ebin/../obj/lib/librpitx.a] Error 2
could not compile dependency :replex, "mix compile" failed. You can recompile this dependency with "mix deps.compile replex", update it with "mix deps.update replex" or clean it with "mix deps.clean replex"
==> try_replex
** (Mix) Could not compile with "make" (exit status: 2).
You need to have gcc and make installed. Try running the
commands "gcc --version" and / or "make --version". If these programs
are not installed, you will be prompted to install them.
```

Questions:
* Is this just something that is wrong with my dev setup?  
* Will this only work on linux?  
* Should I be running in a docker container?

**Comment by jjcarstens** [comment]
Thanks @joelbyler. What host system are you using? I’ve been successful using macOS and Linux.

I’ll give this a look in a bit

**Comment by joelbyler** [comment]
I'm on macOS, 10.14.6 / Mojave

**Comment by jjcarstens** [comment]
Ugh. I know why and its a huge derp on my part (╯°□°）╯︵ ┻━┻ 🤦‍♂

Fix coming up in a bit

**Comment by joelbyler** [comment]
Haha, ok whew, that's a relief.  I was afraid I was doing something very wrong.  Its been a while since I used nerves, your lightning talk inspired me and I'm hoping to hack on some of my kid's toys and get them involved :)

**Comment by jjcarstens** [comment]
K, I just released v0.2.1 with the fixes via https://github.com/jjcarstens/replex/commit/693df0ab61c9fbc37bc7c2af2999b908ded0b043. TL;DR is the patches needed to build with nerves tooling weren't being included in the hex package so it would fail to build there, but not from the repo 🤦‍♂ 

I tested with your repo with `mix deps.update replex && mix firmware` and things built 🎉

**Comment by joelbyler** [comment]
![can_confirm](https://user-images.githubusercontent.com/1151937/68347230-476ae800-00c4-11ea-9003-595e0b2871cd.jpeg)

Can confirm, works for me.  Thanks for making this work so well @jjcarstens !

**Comment by joelbyler** [comment]
@jjcarstens this builds well now, trying to replay an `iq` file that I recorded at 250KHz using the RTL-SDR and rtl_sdr similar to your instructions.  When I attempt to replay the file I get a message `Warning samplerate too high, decimation by 2 will be performed`

My command `Replex.replay(file, 49876000, sample_rate: 250_000)`

Its not 433 MHz like your example though, is that a limitation of this library?

**Comment by jjcarstens** [comment]
Ya, that seems like a bug in sendiq.cpp because it’s limited here
https://github.com/F5OEO/rpitx/blob/master/src/sendiq.cpp#L43

But the help text says that 250k is acceptable
https://github.com/F5OEO/rpitx/blob/master/src/sendiq.cpp#L24

I’ve found that it still works for me even with that error. But we could make another patch to change that line in the file and see what happens?

**Comment by joelbyler** [comment]
Thanks @jjcarstens I can ignore the message if its nothing to worry about.

Dumb Question: Do you have references or can you give advice on what changes with this setup if I want to change from 433 MHz to 49 MHz?  Is it possible to go that low when running off the little jumper wire?  Trying to google to find references for others using this trick and not having much luck.  Thanks for your help and patience!  :)
