### ISSUE TITLE
Unable to replay from rpi4

### ISSUE THREAD

**Issue by jjcarstens** [jjcarstens/replex#8]
Looks like rpi4 behavior is inconsistent - sometimes signal replays, and sometimes it hangs.

Even when `sendiq` succeeds, it seems the signal is not actually transmitted.

`rpitx` currently lists rpi4 as `in beta`, so I assume more investigation into that lib and `librpitx` needs to happen to resolve

**Comment by christomitov** [comment]
Looked a bit more into this and found: https://groups.io/g/rpitx/topic/rpitx_on_pi4_beta/75747197

So I compiled the `pi4` branch of `librpitx` and I got it to work.
